<a href="https://colab.research.google.com/github/soumitra-python/python/blob/main/String.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## ASCII :
A -> 65
B -> 66

In [ ]:
# Vector : array of numbers
# [0.9, 9, 87] --> Embedding

# Embedding : Vector representation of a word/token

In [ ]:
## Main purpose of Embedding :
>> Capturing meaning

###Types of Embeddings :

In [ ]:
1) Frequency based methods :
      -- OHE
      -- Bag-of-words/CountVectorizer
      -- TF-IDF

2) Prediction based methods :
      -- Word2Vec
      -- Glove
      -- FastText
      -- Doc2Vec

In [ ]:
## Sentiment Analysis :
good, best, awesome   --> +ve
bad, worst, aweful    --> -ve

####One Hot Encoding :

In [ ]:
movie is good       --> [movie, is, good]
movie is bad        --> [movie, is, bad]
movie is not good   --> [movie, is, not, good]

vocab = [movie, is, good, bad, not]

movie = [1, 0, 0, 0, 0]
good  = [0, 0, 1, 0, 0]
is  = [0, 1, 0, 0, 0]
not = [0,0, 0,0, 1]

In [ ]:
## Step in OHE
1) Tokenization
2) Create vocab
3) create vector : value of word index in vocab = 1 else 0

In [ ]:
Pro :
>> simple & Intuative

Cons :
>> Semantic meaning is not captured
>> Vector size will increse wil vocab size
>> Sparsity
>> OOV (Out of vocab)

###Bag-of-words/CountVectorizer

In [ ]:
movie is good good  --> [movie, is, good]
movie is bad        --> [movie, is, bad]
movie is not good   --> [movie, is, not, good]

vocab = [movie, is, good, bad, not]

1) [1, 1, 2, 0, 0]
2) [1, 1, 0, 1, 0]
3) [1, 1, 1, 0, 1]

In [ ]:
## Sentiment Analysis :
good, best, awesome   --> +ve
bad, worst, aweful    --> -ve

In [ ]:
review = ["movie is good good",
          "movie is bad",
          "movie is not good"]
sentiment = [1, 0, 0]

In [ ]:
import pandas as pd
df = pd.DataFrame({"review":review, "sentiment":sentiment})
df

review  sentiment
0  movie is good good          1
1        movie is bad          0
2   movie is not good          0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

BoW = CountVectorizer()

In [ ]:
vectors = BoW.fit_transform(df["review"])

In [ ]:
BoW.vocabulary_

{'movie': 3, 'is': 2, 'good': 1, 'bad': 0, 'not': 4}

In [ ]:
vectors[0].toarray()
# movie is good good

array([[0, 2, 1, 1, 0]])

In [ ]:
## Pro :
>> Simple :
>> Explainability :

# Cons :
>> Sparsity on large vocab
>> Vector size will increse wil vocab size
>> Semantic meaning is not captured


###N-gram :

In [ ]:
# This is long movie but not good
# This is not long movie but good

In [ ]:
movie is good good  --> [movie, is, good]
movie is bad        --> [movie, is, bad]
movie is not good   --> [movie, is, not, good]

vocab = [movie, is, good, bad, not]

In [ ]:
This is long movie but not good

unigram = [This, is, long, movie, but, not, good]
bigram = [This is, is long, long movie, movie but, but not, not good]
trigram = [This is long, is long movie, long movie but, movie but not, but not good]

In [ ]:
# ngram_rage : (lower, upper) --> default = (1,1)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

ngram_BoW = CountVectorizer(ngram_range=(3, 5))

vectors = ngram_BoW.fit_transform(df['review'])

In [ ]:
ngram_BoW.vocabulary_

{'movie': 9,
 'is': 3,
 'good': 1,
 'movie is': 10,
 'is good': 5,
 'good good': 2,
 'movie is good': 12,
 'is good good': 6,
 'bad': 0,
 'is bad': 4,
 'movie is bad': 11,
 'not': 14,
 'is not': 7,
 'not good': 15,
 'movie is not': 13,
 'is not good': 8}

In [ ]:
vectors[0].toarray()
# movie is good good
# unigram = [movie, is, good, good]
# bigram = [movie is, is good, good good]
# trigram = [movie is good, is good good

# [0, 2, 1..........]

array([[0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0]])

In [ ]:
## Pro :
>> Simple :
>> Explainability :
>> Compare to CountVectorizer more semantic meaning is captured

# Cons :
>> Sparsity on large vocab
>> Vector size will increse wil vocab size
>> Vector size will increse compare to CountVectorizer

###TF-IDF :

In [ ]:
movie is good good  --> [movie, is, good]
movie is bad        --> [movie, is, bad]
movie is not good   --> [movie, is, not, good]

In [ ]:
TF    --> Term Frequency
IDF   --> Inverse Document Frequency

In [ ]:
TF = no. of times word appeared in a doc / total no. of words in doc

IDF = log(no. of docs / no. of docs containing word)

TF-IDF = TF * IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

vectors = tfidf.fit_transform(df['review'])

In [ ]:
tfidf.get_feature_names_out()

array(['bad', 'good', 'is', 'movie', 'not'], dtype=object)

In [ ]:
vectors[0].toarray()
# movie is good good

array([[0.        , 0.87653717, 0.34035465, 0.34035465, 0.        ]])

In [ ]:
## Frequency based methods :
>> OHE
>> BOW
>> N-gram BoW
>> TF-IDF

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
## Limitations of frequency based :
>> Semantic meaning is not captured
>> Sparsity
>> Vector size will increse with vocab size
>> OOV (Out of vocab)

In [ ]:
##
>> Information Retriever
>> Sentiment analysis
>> Text Classification
>> Clusting
